version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build-and-test : 
    # This is a test job, that runs the tests in the tests folder 
    jobs:
      - test

jobs:
  test:  
    # Using the docker executor and a circleci docker image with python version 3.8 
    docker:
      - image: cimg/python:3.8
    # installing dependencies from the project root's requirements.txt.
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
