version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build-and-test:  
    jobs:
      - build
      - test

jobs:
  build:  
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run :
          name : install python dependencies
          command : |
            pip install --user -r requirements.txt
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - run :
          name : run tests
          command : |
            pytest test/
