version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build-and-test:  
    jobs:
      - run-test

jobs:
  run-test:  
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
