version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build-and-test:  
    jobs:
      - build
      - test

jobs:
  build:  
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - run: python3 test/test_ivp_4_ode.py test_one_var_equations.py
